# Advanced topics {#sec-advanced}

<!-- Advanced topics - separate into chapters later -->

## Are more complex songs more popular?

- "The role of population size in folk tune complexity" [@Street2022]

## Evolution of pitches and intervals

- "Cross-cultural data shows musical scales evolved to maximise imperfect fifths" @McBride2020_CrossculturalDataShows
- "The line of fifths and the co-evolution of tonal pitch-classes" [@Moss2022]

## Stylistic change

The question of historical change is intricably related to musical styles.
Here, we adopt the framework for style analysis layed out by @Meyer1989_StyleMusicTheory.
In particular, the adaptation of @Jan2016 and its schematic representation is already almost 
a description of a statistical graphical model.

- "Statistical Evolutionary Laws in Music Styles" [@Nakamura2019]
- "Investigating style evolution of Western classical music: A computational approach" [@Weiss2019_InvestigatingStyleEvolution]

## Cultural evolution of electronic music 

- "Phylogenetic reconstruction of the cultural evolution of electronic music via dynamic community detection (1975–1999)" [@Youngblood2021_PhylogeneticReconstructionCultural]