# Welcome {.unnumbered}

On these pages you will learn about cultural evolution and music.
The overall aim is to attain a basic understanding of formal models in cultural evolution and learn about several recent approaches that apply them to the domain of music.

We start with a minimal introduction to the [Python](https://www.python.org/) programming language that covers the necessary basic skills in order to follow the remainder of the book. Then, we summarize some general ideas about music and cultural evolution. 

Subsequently, we follow the excellent learning path for computational models in cultural evolution provided by the book [_Individual-based models of cultural evolution: A step-by-step guide using R_](https://acerbialberto.com/IBM-cultevo/) [@Acerbi2022]. These pages comprise a translation of this resource to Python. Finally, we will review and discuss a number of recent publications on music and cultural evolution in the advanced topics section at the end.

:::{.callout}
If you want to refer to this resource, please cite it as appropriately, e.g.: 

Moss, F. C. (2023). _Music memes: Understanding processes of music transmission through cultural evolution modeling_. <https://fabianmoss.github.io/musicmemes>
:::

:::{.callout-important}
The material on this page has been adapted and designed for my musicology research seminar "Music Memes: quantitative approaches and theories of cultural transmission of music" at [Würzburg University](https://uni-wuerzburg.de/), Germany.

Note that the materials here are still under development. Please inform me if you notice any errors or other issues.
:::

##### Acknowledgements {.appendix}

I am grateful for encouragement from [Alberto Acerbi](https://twitter.com/acerbialberto) to continue working on my Python translation of his book and many helpful comments.